# Generated by Django 4.2.1 on 2024-02-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_product_product_details_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='washing_instruction',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
