# Generated by Django 4.2.1 on 2024-02-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_product_washing_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
