# Generated by Django 4.2.1 on 2024-02-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_userprofile_email_userprofile_pin_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
