# Generated by Django 4.2.1 on 2024-02-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_code',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
